<header>
	<div class="wrap white-text">
		<h1>Программное обеспечение <span>hpe software / micro focus</span></h1>
		<h2>для резервного копирования виртуальных, физических и облачных сред, а также управления данными</h2>				
	</div>	
	<div class="top">
		<div class="wrap white-text">
			<div class="left"><span class="target-text">(495) 981-84-84</span><br/>с 10 до 18:30 (многоканальный)</div>
			<a href="https://merlion.com" target="_blank"><img src="https://static.merlion.ru/promo/2017/hpe-software/img/logo_merlion_white.png" alt="MERLION"></a>
			<div class="right"><a class="mail" href="mailto:zapros_hpe_sw@merlion.ru">Zapros_hpe_sw@merlion.ru</a></div>
		</div>			
	</div>
</header>

<div class="menu">
	<div class="wrap">
		<a class="left" href="https://merlion.com" target="_blank"><img src="https://static.merlion.ru/promo/2017/hpe-software/img/logo_merlion.png" alt="MERLION"></a>
		<div class="nav">
			<ul class="columns">
				<li class="col active"><a href="#product">Продукты</a></li>
				<li class="col"><a href="#char">Характеристики</a></li>
				<li class="col"><a href="#arch">Архитектура</a></li>
				<li class="col"><a href="#partner">Партнерам</a></li>
				<li class="col"><a href="#history">Истории успеха</a></li>					
				<li class="col"><a href="#educ">Обучение</a></li>
				<li class="col"><a href="#demo">Демо</a></li>
			</ul>
		</div>
		<a href="#" class="right button">Контакты</a>
	</div>
</div>

<section class="products big-text" id="product">
	<div class="wrap">
		<h2 class="vertical-text">Продукты</h2>
		<div class="col2 left identity">
			<h3>VM Explorer</h3>
			<p>Простой, удобный и недорогой продукт для управления резервным копированием и восстановлением виртуальных сред</p>
			<div class="hidden">Виртуализация - очень популярный в наше время способ «обустройства» ИТ-системы. Одной из важнейших задач, которую приходится решать организациям, желающим виртуализировать свой ИТ-ландшафт, является обеспечение резервного копирования и восстановления после сбоев. Компания HPE представляет простой, недорогой и функциональный продукт, призванный помочь небольшим организациям решить вопрос резервного копирования виртуальных сред Vmware и Hyper-V раз и навсегда.</div>
		</div>
		<div class="col2 left identity">
			<h3>Data Protector</h3>
			<p>Мощный и функциональный инструмент резервного копирования физических и виртуальных сред</p>
			<div class="hidden">Вопрос резервного копирования и восстановления всегда очень остро стоит, и чем больше компания, тем критичнее становится поддержание резервных копий в актуальном состоянии и быстрое восстановление,  а значит, тем более мощными и продуктивными должны быть средства резервного копирования и восстановления. HPE Data Protector - как раз таков, что подтверждается тысячами инсталляций продукта по всему миру и высокими оценками различных обозревателей.</div>
		</div>
		<div class="col2 left identity">
			<h3>Connected Backup</h3>
			<p>Быстрый и удобный инструмент резервного копирования и восстановления рабочих станций, ноутбуков и мобильных устройств</p>
			<div class="hidden">Connected Backup. Сотрудники современных компаний мобильны, темп их работы требует от них быть на связи всегда, работать как из офиса, так и из любого другого места, что значительно увеличивает использование переносных устройств, ноутбуков, планшетов, смартфонов в рабочих целях. Connected Backup – это решение, позволяющее производить резервное копирование end-point устройств, централизованно управлять копиями и политиками, получать доступ к архивным данным из любого места, в любое время.</div>
		</div>
		<div class="col2 left identity">
			<h3>Storage Optimizer</h3>
			<p>Решение по интеллектуальному управлению хранимыми данными и оптимизации контента</p>
			<div class="hidden">HPE Storage Optimizer - это абсолютно новое решение для ИТ-департаментов, желающих сократить затраты и сложность хранения и управления большими объёмами неструктурированных данных. В данное решение встроена аналитическая платформа, комбинирующая лучшее от аналитического ПО HPE Control Point и мощный набор функций для распределения данных по уровням хранения согласно настраиваемым политикам.</div>
		</div>
	</div>
</section>

<section class="big-text" id="char">
	<div class="wrap">
		<h2 class="vertical-text">Характеристики</h2>
		<div class="col2 left identity">
			<div class="target-text">VM Explorer</div>
			<ul class="green-marker">
				<li>Развёртывание и настройка за 5 минут</li>
				<li>Репликация и резервное копирование ESX/ESXi, ESXi free, Hyper-V</li>
				<li>Бэкап на ленты</li>
				<li>Тесты и проверки данных</li>
				<li>Бэкап в облако</li>
				<li>Пофайловое восстановление</li>
				<li>Шифрование</li>
				<li>Поддержка vSAN и vMotion</li>
			</ul>
			<a class="link-arrow" href="https://www.hpe.com/h20195/v2/GetPDF.aspx/4AA6-4147ENN.pdf" target="_blank">Подробнее</a>
		</div>
		<div class="col2 left identity">
			<div class="target-text">Data Protector</div>
			<ul class="green-marker">
				<li>Бэкап физических и виртуальных сред</li>
				<li>Восстановление приложений</li>
				<li>Защита виртуальных серверов</li>
				<li>Интеграция с различными СХД и системами резервного копирования</li>
				<li>Работа с облачными средами</li>
				<li>Автоматизированное восстановление данных</li>
				<li>Управление репликацией и политиками хранения</li>
			</ul>
			<a class="link-arrow" href="https://www.hpe.com/h20195/V2/getpdf.aspx/c04109270.pdf" target="_blank">Подробнее</a>
		</div>
		<div class="col2 left identity">
			<div class="target-text">Connected Backup</div>
			<ul class="green-marker">
				<li>Бэкап ноутбуков, рабочих станций, планшетов и смартфонов</li>
				<li>Масштабируемость корпоративного уровня</li>
				<li>Дедупликация и сжатие данных</li>
				<li>Доступ к данным с мобильным устройств</li>
				<li>Гибкие варианты развёртывания, включая облачные и гибридные конфигурации</li>
			</ul>
			<a class="link-arrow" href="https://www.hpe.com/h20195/V2/getpdf.aspx/4AA5-7728ENW.pdf" target="_blank">Подробнее</a>
		</div>
		<div class="col2 left identity">
			<div class="target-text">Storage Optimizer</div>
			<ul class="green-marker">
				<li>Эффективное управление местом, занимаемым различными данными</li>
				<li>Аналитика частоты доступа к данным</li>
				<li>Аналитика по типам файлов</li>
				<li>Управление уровнями хранения и местами хранения данных, оптимизация хранения</li>
			</ul>
			<a class="link-arrow" href="http://www.storagenews.ru/64/HPE_SO_64.pdf" target="_blank">Подробнее</a>
		</div>
	</div>
</section>

<section class="architecture" id="arch">
	<div class="gray small-block">
		<div class="wrap">
			<h2 class="vertical-text">Архитектура</h2>
			<div class="col">
				<div class="target-text">VM Explorer</div>
				<ul>
					<li>Резервное копирование</li>
					<li>Репликация</li>
					<li>Мгновенное восстановление</li>
					<li>Поддержка аппаратных снэпшотов</li>
				</ul>
				<div><a class="button open-form" href="#">Есть вопросы?</a></div>
			</div>
			<img class="col" src="https://static.merlion.ru/promo/2017/hpe-software/img/vm_explorer_blue.jpg" alt="VM Explorer" />
		</div>
	</div>

	<div class="small-block">
		<div class="wrap">
			<div class="col">
				<div class="target-text">Data Protector</div>
				<div><a class="button open-form" href="#">Есть вопросы?</a></div>
			</div>
			<img class="col" src="https://static.merlion.ru/promo/2017/hpe-software/img/data_protector_blue.jpg" alt="Data Protector" />
		</div>
	</div>

	<div class="gray small-block">
		<div class="wrap">
			<div class="col">
				<div class="target-text">Connected Backup</div>
				<div><a class="button open-form" href="#">Есть вопросы?</a></div>
			</div>
			<img class="col" src="https://static.merlion.ru/promo/2017/hpe-software/img/connect_backup_blue.jpg" alt="VM Explorer" />
		</div>
	</div>

	<div class="small-block">
		<div class="wrap">
			<div class="col">
				<div class="target-text">Storage Optimizer</div>
				<div><a class="button open-form" href="#">Есть вопросы?</a></div>
			</div>
			<img class="col" src="https://static.merlion.ru/promo/2017/hpe-software/img/storage_optimizer_blue.jpg" alt="Data Protector" />
		</div>
	</div>
</section>

<section class="partner graphite big-text" id="partner">
	<div class="wrap">
		<h2 class="vertical-text">Партнерам</h2>
		<h4>Продажа Программного обеспечения HPE Software для резервного копирования и управления данными</h4>
		<ul class="white-marker white-text">
			<li>Работа с лидером индустрии</li>
			<li>Выгодная партнёрская программа</li>
			<li>Доступ к специальным ценам</li>
			<li>Большая инсталлированная база ПО – уже есть, с чем работать</li>
			<li>Помощь со стороны Merlion в части предпродажной подготовки, расчёта и внедрения продуктов</li>
		</ul>
		<div><a class="button white open-form" href="#">Есть вопросы?</a></div>
	</div>
</section>

<section class="history" id="history">
	<div class="wrap">
		<h2 class="vertical-text">Истории<span>успеха</span></h2>
		<div class="col2 left">
			<div class="target-text">VM Explorer</div>
			<div class="quote">&Prime;То, что раньше занимало дни, теперь делается за минуты&Prime;</div>
			<p>Brennan Sandusky, Systems Director, ZaneRay Group</p>
			<div><iframe width="398" height="224" src="https://www.youtube.com/embed/EX0dBry9Qbo?list=PLlUdEXI83_Xpcct0T-QpbwySoVdAhgrcX" frameborder="0" allowfullscreen></iframe></div>
		</div>
		<div class="col2 left">
			<div class="target-text">Data Protector</div>
			<div class="quote">&Prime;Я могу спокойно уйти домой и быть уверенным, что наши данные защищены&Prime;</div>
			<p>David Lewis, Senior IT Program Manager, Microsoft</p>
			<div><iframe width="398" height="224" src="https://www.youtube.com/embed/b2rUnNgshZ4?rel=0" frameborder="0" allowfullscreen></iframe></div>
		</div>
		<div class="col2 left">
			<div class="target-text">Connected Backup</div>
			<div><iframe width="398" height="224" src="https://www.youtube.com/embed/SG6qjOtEnvA?rel=0" frameborder="0" allowfullscreen></iframe></div>
		</div>
		<div class="col2 left">
			<div class="target-text">Storage Optimizer</div>
			<div><iframe width="398" height="224" src="https://www.youtube.com/embed/P-vmPXqvHDA?rel=0" frameborder="0" allowfullscreen></iframe></div>
		</div>
	</div>
</section>

<section class="education" id="educ">
	<div class="wrap">
		<h2 class="vertical-text">Обучение</h2>
		<a class="target-text link-arrow col" href="https://www.brighttalk.com/service/player/ru-RU/theme/default/channel/13185/webcast/209003/play" target="_blank">VM Explorer</a>
		<a class="target-text link-arrow col" href="https://www.brighttalk.com/service/player/ru-RU/theme/default/channel/13185/webcast/215841/play" target="_blank">Data Protector</a>
		<img src="https://static.merlion.ru/promo/2017/hpe-software/img/main_education_blue.jpg" alt="HP Software Обучение" />
	</div>		
</section>

<section class="demo graphite white-text" id="demo">
	<div class="wrap big-text zoom-block">
		<h2 class="vertical-text">Демо</h2>
		<div class="col2 left">
			<div class="target-text">Загрузите пробные версии <span>самостоятельно</span></div>
			<ul>
				<li><a class="link-arrow" href="https://saas.hpe.com/try/freevm-server-backup" target="_blank">VM Explorer</a></li>
				<li><a class="link-arrow" href="https://saas.hpe.com/ru-ru/signup/try/data-protector" target="_blank">Data Protector</a></li>
				<li><a class="link-arrow" href="http://go.saas.hpe.com/trial-request/connected-mx" target="_blank">Connected Backup</a></li>
			</ul>
		</div>
		<div class="col2 left">
			<div class="target-text"><span>Свяжитесь с нами</span> по поводу пробных версий</div>
			<ul>
				<li>Storage Optimizer</li>
				<li class="mode"><span class="target-text">(495) 981-84-84</span><br/>с 10 до 18:30 (многоканальный)</li>
				<li><a class="mail" href="mailto:zapros_hpe_sw@merlion.ru">Zapros_hpe_sw@merlion.ru</a></li>
			</ul>
		</div>
	</div>
</section>

<div class="overlay"></div>
<div class="popup">
	<h2 class="vertical-text">Обратная связь</h2>
	<p>Если у Вас появились вопросы по продуктам, воспользуйтесь данной формой</p>
	<?php
		$programID=1738;
        if ($_SERVER["REQUEST_METHOD"] == "POST") {
              include "forms/post.php";
        } else {
            ob_start();
            include "forms/form.php";
            $form = ob_get_clean();
            echo $form;
        }
	?>
</div>